name: TRAXXIA-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - master

variables:
  MAJOR: 1        # Increment manually for major changes
  MINOR: 0        # Increment manually for minor features
  PATCH: $[counter(format('{0}.{1}', variables['MAJOR'], variables['MINOR']), 0)]

  SEMVER: $(MAJOR).$(MINOR).$(PATCH).$(Build.BuildId)
  IMAGE_VERSION: $(SEMVER)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image for frontend
    jobs:
      - job: BuildJob
        displayName: Build Docker Image and Push to ACR
        pool:
          vmImage: 'ubuntu-latest'

        # variables:
        #   - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
        #       - group: traxxia-frontend

        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          # Dynamically set IMAGE_NAME
          - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
            - script: echo "##vso[task.setvariable variable=IMAGE_NAME]traxxia_frontend"
              displayName: 'Set IMAGE_NAME (master)'

          # Generate .env dynamically
          # - script: |
          #     cd docker/services/product-client
          #     rm -f .env
          #     echo 'NODE_PATH=$(NODE_PATH)' >> .env
          #     cat .env
          #     cd ../../..
          #   displayName: 'Generated .env file ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓'

          # - task: npmAuthenticate@0
          #   inputs:
          #     workingFile: '$(System.DefaultWorkingDirectory)/docker/services/product-client/.npmrc'
          #   displayName: 'Authenticate npm'

          - task: Docker@2
            displayName: 'Build and Push Traxxia FE Docker Image to ACR'
            inputs:
              containerRegistry: 'sc-traxxia'     # Use your ACR service connection
              repository: $(IMAGE_NAME)
              command: buildAndPush
              Dockerfile: 'docker/Dockerfile'
              tags: |
                latest
                $(IMAGE_VERSION)

          - script: echo "Docker Image tagged as $(IMAGE_NAME):$(IMAGE_VERSION)"
            displayName: 'Output Docker Tag'
