name: TRAXXIA-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - master
      - develop

variables:
  MAJOR: 1        # Increment manually for major changes
  MINOR: 0        # Increment manually for minor features
  PATCH: $[counter(format('{0}.{1}', variables['MAJOR'], variables['MINOR']), 0)]

  SEMVER: $(MAJOR).$(MINOR).$(PATCH).$(Build.BuildId)
  IMAGE_VERSION: $(SEMVER)
  IMAGE_NAME: trax_dev_frontend

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image for frontend
    jobs:
      - job: BuildJob
        displayName: Build Docker Image and Push to ACR
        pool:
          vmImage: 'ubuntu-latest'

        variables:
          - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
              - group: trax-dev-fe-vg

        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          # Generate .env dynamically
          - script: |
              rm -f .env
              echo 'REACT_APP_BACKEND_URL=$(REACT_APP_BACKEND_URL)' >> .env
              cat .env
            displayName: 'Generated .env file ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓'

          # - task: npmAuthenticate@0
          #   inputs:
          #     workingFile: '$(System.DefaultWorkingDirectory)/docker/services/product-client/.npmrc'
          #   displayName: 'Authenticate npm'

          - task: Docker@2
            displayName: 'Build and Push Traxxia FE Docker Image to ACR'
            inputs:
              containerRegistry: 'trax-sc-dev-acr'     # Use your ACR service connection
              repository: $(IMAGE_NAME)
              command: buildAndPush
              Dockerfile: 'docker/Dockerfile'
              tags: |
                latest
                $(IMAGE_VERSION)

          - script: echo "Docker Image tagged as $(IMAGE_NAME):$(IMAGE_VERSION)"
            displayName: 'Output Docker Tag'
