export const AI_PAGE_CONTEXTS = {
    AHA: {
        current_page: "PMF AHA Card Dashboard",
        page_description: "This page presents key strategic insights based on your onboarding. These are dynamically generated insights relevant to the business context (e.g., product-market fit, market trends, core capabilities, adjacencies, and risks)."
    },
    EXECUTIVE_SUMMARY: {
        current_page: "PMF Executive Summary Dashboard",
        page_description: "This page displays the executive summary of the Product-Market-Fit analysis, highlighting adjacencies to explore, competitive levers, and top priorities."
    },
    PRIORITIES: {
        current_page: "PMF Priorities Dashboard",
        page_description: "It bridges the gap between strategy and execution. It identifies strategic priorities (typically the top 3–5 priorities) and breaks them down into specific tactical projects that can be tracked."
    },
    ADVANCED: {
        current_page: "Advanced Dashboard",
        page_description: "It allows users to view, manage, and edit all the qualitative and quantitative business information that feeds into the AI's strategic analysis. It acts as an editable brief of everything the AI knows about the business. The Page content is being shared which consist of question and answer pairs."
    },
    INSIGHTS: {
        current_page: "Insights Dashboard",
        page_description: "The Insights Dashboard is where you view and analyze the strategic outputs generated by the AI based on that data."
    },
    STRATEGIC: {
        current_page: "Strategic Dashboard",
        page_description: "The Strategic Dashboard (labeled as S.T.R.A.T.E.G.I.C) is designed to provide comprehensive, actionable strategic recommendations and an execution roadmap."
    },
    PROJECTS: {
        current_page: "Projects Dashboard",
        page_description: "The Project Dashboard is where strategy becomes reality. It takes the ideas generated in the S.T.R.A.T.E.G.I.C tab, helps your team prioritize them effectively using both human and AI input, and provides a structured environment to track their execution status over time."
    },
    PROJECT_CREATE: {
        current_page: "Project create page",
        page_description: "The Project Create Page (or New Project screen) is a structured form designed to move an idea or strategic recommendation from concept to an actionable execution plan."
    },
    PROJECT_EDIT: {
        current_page: "Project edit page",
        page_description: "The Edit Page functions as the active, collaborative workspace for managing the project through its entire execution lifecycle."
    }
};
