name: TRAXXIA Frontend CI

on:
  push:
    branches: [QA]
  pull_request:
    branches: [QA]

env:
  IMAGE_NAME: traxxia_qa_frontend
  REGISTRY: ${{ secrets.QA_ACR_LOGIN_SERVER }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image version
        id: version
        run: echo "IMAGE_VERSION=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Debug ENV
        run: |
          echo "BACKEND=${{ vars.QA_APP_BACKEND_URL }}"
          echo "ML=${{ vars.QA_APP_ML_BACKEND_URL }}"
          echo "STRIPE=${{ vars.QA_APP_STRIPE_PUBLISHABLE_KEY }}"

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.QA_ACR_LOGIN_SERVER }}
          username: ${{ secrets.QA_ACR_USERNAME }}
          password: ${{ secrets.QA_ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate .env for Docker Build
        run: |
          echo "REACT_APP_BACKEND_URL=${{ vars.QA_APP_BACKEND_URL }}" >> .env
          echo "REACT_APP_ML_BACKEND_URL=${{ vars.QA_APP_ML_BACKEND_URL }}" >> .env
          echo "REACT_APP_ENABLE_PMF=${{ vars.QA_APP_ENABLE_PMF }}" >> .env
          echo "REACT_APP_AI_CHAT_URL=${{ vars.QA_APP_AI_CHAT_URL }}" >> .env
          echo "REACT_APP_STRIPE_PUBLISHABLE_KEY=${{ vars.QA_APP_STRIPE_PUBLISHABLE_KEY }}" >> .env

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ secrets.QA_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.QA_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.IMAGE_VERSION }}

      - name: Output image tag
        run: |
          echo "Image pushed: ${{ secrets.QA_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.IMAGE_VERSION }}"